version: '3.9'
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db
      
  mongo-express:
    image: mongo-express
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:secret@mongo:27017/
      
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/
    depends_on:
      - mongo
      
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - mongo
      - rabbitmq
      - redis
  
volumes:
  mongo_data:
  redis_data: