apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    app: asyncop
    version: {{.Chart.AppVersion}}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://asyncop:5000;
        }
      }
    }
