@startuml

' Set direction and skin parameters
top to bottom direction
skinparam agent {
    BackgroundColor LightCoral
}
skinparam componentStyle uml2
skinparam component {
    BackgroundColor White
    BorderColor Black
}

' Define agents and components
'agent "Docker" as Docker
[RabbitMQ]
[Redis]
[FastAPI]
[Uvicorn]
[Celery\nworker] as Celery
database "MongoDB" as DB
[Streamlit\nDashboard] as Streamlit

' Define connections
'Docker -[#blue]-> Flower
'Docker -[#blue]-> Gunicorn
Celery <-> DB
'Docker -[#blue]-> Celery
Celery <-> RabbitMQ
Celery <-> Redis
Uvicorn --> FastAPI
FastAPI <-> Celery
Streamlit -[#blue]-> DB

@enduml
