@startuml

skinparam activity {
    BorderColor DarkSlateGray
    BackgroundColor LightBlue
}

start
:Soumission de commande par le client;
if (Commande est valide ?) then (oui)
    :Vérification de la commande par un employé;
    if (Commande est acceptée ?) then (oui)
        :Génération du devis;
        if (Devis généré avec succès ?) then (oui)
            :Validation du devis par un employé;
            if (Devis validé ?) then (oui)
                :Accord du client;
                if (Client accepte le devis ?) then (oui)
                    :Assignation de la réalisation de la commande;
                    if (Réalisation terminée ?) then (oui)
                        :Notification au client;
                    else (non)
                        :Progression de la réalisation;
                    endif
                else (non)
                    stop
                endif
            else (non)
                stop
            endif
        else (non)
            stop
        endif
    else (non)
        stop
    endif
else (non)
    stop
endif

@enduml
