@startuml

' left to right direction
top to bottom direction

agent "\nRabbitMQ\n" as RabbitMQ
agent "\n       <B>Prism\n(mocked service)\n" as prism
skinparam agentbackgroundColor LightCoral

[Flower]
[FastAPI]
[Celery \nWorker] as Celery_Worker
[Celery \nClient] as Celery_client
[Redis] as Redis
database "\nMongoDB\n" as DB #LightCoral


FastAPI -> Celery_client
Celery_client -> RabbitMQ
RabbitMQ -> Celery_Worker
Celery_Worker -> Redis
FastAPI <-> DB
Celery_Worker .-> prism
Flower <-> RabbitMQ


@enduml
