apiVersion: v1
kind: ConfigMap
metadata:
  name: asyncop-config
  namespace: asyncop-project
data: 
  VERSION: "1.6.2"
  SERVICE_NAME: 'ProcessingService'
  NAME: "Asynchronuous Order Processing"
  LOG_LEVEL: "debug"