apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: asyncop
    version: {{.Chart.AppVersion}}
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0
